### ISSUE TITLE
Добавить тег 1c-enterprise в описании репозитория

### ISSUE THREAD

**Issue by Bayselonarrend** [kovalevdmv/onec_comp_gen#2]
Здравствуйте. У вас очень крутой проект. Не могли бы вы добавить в настройках описания репозитория topic `1c-enterprise`? Тогда он попадет в агрегатор [OpenYellow](https://github.com/OpenBSL/OpenYellow) + его tg-канал и о нем узнает больше людей

![image](https://github.com/user-attachments/assets/642b59a0-0a40-4db6-b1ba-61da22a0a5ee)

Спасибо

**Comment by kovalevdmv** [comment]
Добавлен топик 1c-enterprise
